minimum_trust_level_to_create_TOC:
  default: 0
  type: enum
  choices:
    - 1
    - 2
    - 3
    - 4
table_of_contents_icon:
  default: "align-left"
anchor_icon:
  default: "hashtag"
composer_toc_text:
  default: "This topic will contain a table of contents"
